/**
 * Product catalog. Prices are integer cents — never floats.
 *
 * `art` + `palette` drive the generated artwork (see svg.js); the build step
 * rasterizes each one to PNG under public/images/.
 */

export const products = [
  {
    id: 'aurora-over-ear',
    name: 'Aurora Over-Ear Headphones',
    tagline: 'Studio-grade sound, 40-hour battery',
    description:
      'Aurora pairs 40mm titanium drivers with adaptive noise cancelling that samples the room 200 times a second. Memory-foam earcups stay comfortable through a full workday, and a 10-minute charge buys you six hours of playback.',
    price: 1499900,
    compareAtPrice: 1799900,
    category: 'Audio',
    tags: ['wireless', 'noise-cancelling', 'over-ear'],
    rating: 4.8,
    reviews: 412,
    stock: 24,
    featured: true,
    art: 'headphones',
    palette: 'indigo',
    specs: { Driver: '40mm titanium', Battery: '40 hours', Weight: '268 g', Connectivity: 'Bluetooth 5.3 / USB-C' },
  },
  {
    id: 'drift-runner',
    name: 'Drift Runner Sneakers',
    tagline: 'Everyday cushioning that does not quit',
    description:
      'A knit upper that breathes, over a dual-density foam midsole tuned for long days on pavement. The outsole uses a recycled rubber compound with 30% more abrasion resistance than our last generation.',
    price: 649900,
    compareAtPrice: null,
    category: 'Footwear',
    tags: ['running', 'unisex', 'recycled'],
    rating: 4.6,
    reviews: 987,
    stock: 61,
    featured: true,
    art: 'sneaker',
    palette: 'ember',
    specs: { Upper: 'Recycled knit', Drop: '8 mm', Weight: '242 g (US 9)', Use: 'Road / daily' },
  },
  {
    id: 'trail-runner-olive',
    name: 'Trail Runner, Olive',
    tagline: 'Grip for loose ground',
    description:
      'Deeper 5mm lugs and a rock plate underfoot make this the shoe for fire roads and singletrack. A gusseted tongue keeps grit where it belongs — outside the shoe.',
    price: 799900,
    compareAtPrice: 949900,
    category: 'Footwear',
    tags: ['trail', 'grip', 'outdoor'],
    rating: 4.5,
    reviews: 233,
    stock: 18,
    featured: false,
    art: 'sneaker',
    palette: 'forest',
    specs: { Lugs: '5 mm', Plate: 'Nylon rock plate', Weight: '286 g (US 9)', Use: 'Trail' },
  },
  {
    id: 'meridian-watch',
    name: 'Meridian Automatic Watch',
    tagline: '38mm case, sapphire crystal',
    description:
      'A 21-jewel automatic movement with a 42-hour power reserve, wrapped in brushed steel and capped with anti-reflective sapphire. Water resistant to 100 metres.',
    price: 2499900,
    compareAtPrice: null,
    category: 'Accessories',
    tags: ['automatic', 'sapphire', 'steel'],
    rating: 4.9,
    reviews: 156,
    stock: 7,
    featured: true,
    art: 'watch',
    palette: 'slate',
    specs: { Case: '38 mm steel', Movement: '21-jewel automatic', Reserve: '42 hours', Water: '10 ATM' },
  },
  {
    id: 'transit-backpack',
    name: 'Transit 24L Backpack',
    tagline: 'Carry-on friendly, laptop safe',
    description:
      'Twenty-four litres organised properly: a suspended 16" laptop sleeve, a quick-grab top pocket, and a clamshell main compartment that opens flat for security lines. Made from recycled 420D ripstop.',
    price: 499900,
    compareAtPrice: 599900,
    category: 'Bags',
    tags: ['travel', 'laptop', 'recycled'],
    rating: 4.7,
    reviews: 604,
    stock: 33,
    featured: true,
    art: 'backpack',
    palette: 'ocean',
    specs: { Volume: '24 L', Laptop: 'Up to 16"', Fabric: 'Recycled 420D ripstop', Weight: '1.1 kg' },
  },
  {
    id: 'field-camera',
    name: 'Field Mirrorless Camera',
    tagline: '26MP APS-C with in-body stabilisation',
    description:
      'A weather-sealed body built around a 26 megapixel back-illuminated sensor and five-axis stabilisation worth about 6.5 stops. Shoots 4K60 with 10-bit colour straight to card.',
    price: 8999900,
    compareAtPrice: 9999900,
    category: 'Tech',
    tags: ['camera', 'mirrorless', '4k'],
    rating: 4.8,
    reviews: 89,
    stock: 5,
    featured: false,
    art: 'camera',
    palette: 'slate',
    specs: { Sensor: '26 MP APS-C BSI', Stabilisation: '5-axis, 6.5 stops', Video: '4K60 10-bit', Sealing: 'Weather sealed' },
  },
  {
    id: 'potter-mug',
    name: 'Potter Stoneware Mug',
    tagline: '350ml, reactive glaze, no two alike',
    description:
      'Thrown from a high-fire stoneware body and finished in a reactive glaze that pools differently on every piece. Dishwasher and microwave safe, despite looking far too precious for either.',
    price: 89900,
    compareAtPrice: null,
    category: 'Home',
    tags: ['ceramic', 'handmade', 'kitchen'],
    rating: 4.4,
    reviews: 1204,
    stock: 140,
    featured: false,
    art: 'mug',
    palette: 'sunset',
    specs: { Volume: '350 ml', Material: 'Stoneware', Care: 'Dishwasher safe', Origin: 'Made in Portugal' },
  },
  {
    id: 'lounge-chair',
    name: 'Lound Lounge Chair',
    tagline: 'Moulded shell on solid oak legs',
    description:
      'A pressure-moulded shell with a lumbar curve that was revised eleven times before it felt right. Solid oak legs, felt floor pads, and a seat height that works at a desk or a dining table.',
    price: 1899900,
    compareAtPrice: 2199900,
    category: 'Home',
    tags: ['furniture', 'oak', 'seating'],
    rating: 4.6,
    reviews: 178,
    stock: 12,
    featured: true,
    art: 'chair',
    palette: 'sand',
    specs: { Legs: 'Solid oak', 'Seat height': '46 cm', Load: '120 kg', Assembly: '4 bolts, tool included' },
  },
  {
    id: 'halo-desk-lamp',
    name: 'Halo Desk Lamp',
    tagline: 'Tunable white, 2700K to 6000K',
    description:
      'A weighted base that will not tip, a friction arm that stays exactly where you put it, and a diffuser that spreads light without a hot spot. Dim from 5% to full with a single touch strip.',
    price: 299900,
    compareAtPrice: null,
    category: 'Home',
    tags: ['lighting', 'desk', 'dimmable'],
    rating: 4.5,
    reviews: 342,
    stock: 46,
    featured: false,
    art: 'lamp',
    palette: 'sand',
    specs: { Colour: '2700K–6000K', Output: '650 lumens', Power: '9 W', Dimming: '5%–100% touch' },
  },
  {
    id: 'clack-65-keyboard',
    name: 'Clack 65 Mechanical Keyboard',
    tagline: 'Gasket mount, hot-swap, wireless',
    description:
      'A 65% aluminium board on a gasket mount, with three layers of foam so it sounds like a thock rather than a rattle. Hot-swap sockets take any five-pin switch, and it runs wired or over 2.4GHz.',
    price: 899900,
    compareAtPrice: 999900,
    category: 'Tech',
    tags: ['keyboard', 'hot-swap', 'wireless'],
    rating: 4.7,
    reviews: 521,
    stock: 29,
    featured: true,
    art: 'keyboard',
    palette: 'plum',
    specs: { Layout: '65%', Mount: 'Gasket', Switches: 'Hot-swap 5-pin', Connection: 'USB-C / 2.4G / BT' },
  },
  {
    id: 'monstera-potted',
    name: 'Monstera in Ceramic Pot',
    tagline: 'Live plant, ships in its planter',
    description:
      'A well-established Monstera deliciosa, about 60cm tall, already showing fenestrations. Arrives potted in a glazed ceramic planter with a drainage layer, so there is nothing to repot on day one.',
    price: 129900,
    compareAtPrice: null,
    category: 'Home',
    tags: ['plant', 'live', 'indoor'],
    rating: 4.3,
    reviews: 267,
    stock: 21,
    featured: false,
    art: 'plant',
    palette: 'forest',
    specs: { Height: '~60 cm', Light: 'Bright indirect', Water: 'Weekly', Pot: 'Glazed ceramic, 16 cm' },
  },
  {
    id: 'coastline-sunglasses',
    name: 'Coastline Polarised Sunglasses',
    tagline: 'Category 3 polarised, acetate frame',
    description:
      'Hand-polished acetate frames with polarised category 3 lenses that cut glare off water and asphalt. Spring hinges mean they survive being shoved in a bag.',
    price: 599900,
    compareAtPrice: 699900,
    category: 'Accessories',
    tags: ['polarised', 'acetate', 'uv400'],
    rating: 4.4,
    reviews: 398,
    stock: 55,
    featured: false,
    art: 'sunglasses',
    palette: 'ocean',
    specs: { Lens: 'Polarised cat. 3', Protection: 'UV400', Frame: 'Italian acetate', Hinges: 'Sprung' },
  },
  {
    id: 'summit-bottle',
    name: 'Summit 750ml Insulated Bottle',
    tagline: '24 hours cold, 12 hours hot',
    description:
      'Double-walled 18/8 stainless with a copper-lined vacuum layer. The lid seals with a single quarter-turn and the mouth is wide enough for ice cubes but narrow enough to drink from without wearing it.',
    price: 149900,
    compareAtPrice: null,
    category: 'Outdoors',
    tags: ['insulated', 'steel', 'bpa-free'],
    rating: 4.7,
    reviews: 1533,
    stock: 210,
    featured: false,
    art: 'bottle',
    palette: 'ember',
    specs: { Volume: '750 ml', Cold: '24 hours', Hot: '12 hours', Material: '18/8 stainless' },
  },
  {
    id: 'pulse-speaker',
    name: 'Pulse Portable Speaker',
    tagline: 'IP67, 20-hour battery, stereo pairing',
    description:
      'Two full-range drivers and a passive radiator in a body you can drop in a lake and fish out again. Pair two for proper stereo, or chain up to eight for something louder than the neighbours will enjoy.',
    price: 449900,
    compareAtPrice: 599900,
    category: 'Audio',
    tags: ['bluetooth', 'waterproof', 'portable'],
    rating: 4.5,
    reviews: 726,
    stock: 74,
    featured: false,
    art: 'speaker',
    palette: 'plum',
    specs: { Rating: 'IP67', Battery: '20 hours', Pairing: 'Stereo + 8-device chain', Charge: 'USB-C' },
  },
  {
    id: 'market-tote',
    name: 'Market Canvas Tote',
    tagline: '16oz canvas, reinforced base',
    description:
      'Heavyweight 16oz cotton canvas with a double-stitched base panel and webbing handles rated well past what you will ever put in it. Washes flat, softens with age.',
    price: 99900,
    compareAtPrice: null,
    category: 'Bags',
    tags: ['canvas', 'everyday', 'cotton'],
    rating: 4.2,
    reviews: 845,
    stock: 168,
    featured: false,
    art: 'tote',
    palette: 'sunset',
    specs: { Fabric: '16 oz cotton canvas', Capacity: '20 L', Handles: 'Webbing, 60 cm', Care: 'Machine wash cold' },
  },
  {
    id: 'echo-earbuds',
    name: 'Echo Wireless Earbuds',
    tagline: 'ANC in 4.6 grams per side',
    description:
      'Hybrid active noise cancelling with a transparency mode that actually sounds like the room rather than a microphone. Six hours per bud, twenty-four more in the case.',
    price: 499900,
    compareAtPrice: 599900,
    category: 'Audio',
    tags: ['earbuds', 'anc', 'wireless'],
    rating: 4.6,
    reviews: 1102,
    stock: 88,
    featured: true,
    art: 'earbuds',
    palette: 'indigo',
    specs: { ANC: 'Hybrid, 42 dB', Battery: '6 h + 24 h case', Weight: '4.6 g per bud', Rating: 'IPX4' },
  },
];

export const categories = [...new Set(products.map((p) => p.category))].sort();

export function findProduct(id) {
  return products.find((p) => p.id === id) || null;
}
